

export let dataCradGame = {
  "CASINO": [
    {
      "s_type": "CASINO",
      "s_pbrand_code": "SA",
      "s_brand_code": "B001",
      "s_brand_name": "SAGame",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/6.png",
      "s_endpoint_access": "/SA/LoginRequest"
    },
    {
      "s_type": "CASINO",
      "s_pbrand_code": "SEXY",
      "s_brand_code": "B003",
      "s_brand_name": "SexyGame",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/4.png",
      "s_endpoint_access": "/SEXY/LoginRequest"
    },
    {
      "s_type": "CASINO",
      "s_pbrand_code": "PP",
      "s_brand_code": "B008",
      "s_brand_name": "PragmaticPlay - Live",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/8.png",
      "s_endpoint_access": "/PP/LIVE/LoginRequest"
    }
  ],
  "SLOT": [
    {
      "s_type": "SLOT",
      "s_pbrand_code": "PG",
      "s_brand_code": "B006",
      "s_brand_name": "PGSoft",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/1.png",
      "s_endpoint_access": "/PG/LoginRequestNew"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "JOKER",
      "s_brand_code": "B009",
      "s_brand_name": "JOKER",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/assets/images/cradCategoryGame/11.png",
      "s_endpoint_access": "/JOKER/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "SIMPLEPLAY",
      "s_brand_code": "B010",
      "s_brand_name": "SimplePlay",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/3.png",
      "s_endpoint_access": "/SIMPLEPLAY/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "PPS",
      "s_brand_code": "B011",
      "s_brand_name": "PragmaticPlay - Slot",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/assets/images/cradCategoryGame/8.png",
      "s_endpoint_access": "/PP/SLOT/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "HB",
      "s_brand_code": "B016",
      "s_brand_name": "Habanero",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/13.png",
      "s_endpoint_access": "/HABANERO/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "JILI",
      "s_brand_code": "B017",
      "s_brand_name": "Jili",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/12.png",
      "s_endpoint_access": "/Jili/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "FC",
      "s_brand_code": "B018",
      "s_brand_name": "Fachai",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "",
      "s_endpoint_access": "/FC/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "RSG",
      "s_brand_code": "B032",
      "s_brand_name": "Royal Slot Gaming",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/assets/images/cradCategoryGame/15.png",
      "s_endpoint_access": "/RSG/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "YG",
      "s_brand_code": "B019",
      "s_brand_name": "Ygg",
      "s_status": "A",
      "s_status_agent": "C",
      "s_lobby_flg": "Y",
      "s_lobby_url": "",
      "s_endpoint_access": "/DCS/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "PNG",
      "s_brand_code": "B027",
      "s_brand_name": "Play N GO",
      "s_status": "A",
      "s_status_agent": "C",
      "s_lobby_flg": "Y",
      "s_lobby_url": "",
      "s_endpoint_access": "/DCS/LoginRequest"
    }

  ],
  "SPORT": [
    {
      "s_type": "SPORT",
      "s_pbrand_code": "SBO",
      "s_brand_code": "B012",
      "s_brand_name": "Sbobet",
      "s_status": "A",
      "s_status_agent": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "/assets/images/cradCategoryGame/5.png",
      "s_endpoint_access": "/SBO/LoginRequest"
    }
  ],
  "FISHING": [
    {
      "s_game_type": "Fishing",
      "s_game_code": "xq9ohbyf9m79o",
      "s_game_name": "Bird Paradise",
      "s_game_alias": "FishHunterBirdHunter",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "91",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/xq9ohbyf9m79o.png",
      "d_create": "2021-09-04 15:18:25",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4ZWZaZlk2N3VYYWF5YWhJclpsTDZxVmxwYmVZdjBBN29zd0FpL1cxYVFZWg==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "p63ornyjba8oa",
      "s_game_name": "Fishermans Wharf",
      "s_game_alias": "FishermansWharf",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "149",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/p63ornyjba8oa.png",
      "d_create": "2021-09-04 15:18:25",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4Y1VKcWYwODExMVpCM002R1RLRDBLdEliSUFMbHYrcDYzcW5qMXBDQU44Zg==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "ddpg1amgc71gk",
      "s_game_name": "Insect Paradise",
      "s_game_alias": "FishHunterInsectParadise",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "92",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/ddpg1amgc71gk.png",
      "d_create": "2021-09-04 15:18:25",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4WlI0bE5JVkt0RU0xUFRHamU4T3FaWmtqajB2YVZ0eTkvb0wzWXVUZ09GQw==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "st5cmuqnaxycn",
      "s_game_name": "Fish Hunting: Happy Fish 5",
      "s_game_alias": "FishHunterHappyFish5",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "61",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/st5cmuqnaxycn.png",
      "d_create": "2021-09-04 15:18:24",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4Ylk2ZDFXNngwb3pub3QxSzlkbWxva3NCVEd2NU83OWNRdTFqakUrL0w1Qw==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "4omkmmpnwqokn",
      "s_game_name": "Fish Hunter Spongebob",
      "s_game_alias": "FishSpongebob",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "107",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/4omkmmpnwqokn.png",
      "d_create": "2021-09-04 15:18:24",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4VnFRaEEvVzRTakE0SHpSci9mQm1sYXV4QjJlemt6Z2t5YXJFcmpqNnBsOQ==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "wi17jwsu4de7c",
      "s_game_name": "Fish Hunting: Yao Qian Shu",
      "s_game_alias": "FishMoneyTree",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "20",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/wi17jwsu4de7c.png",
      "d_create": "2021-09-04 15:18:24",
      "d_update": "2024-04-01 12:59:29",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4VkV3ZXdLckxnT0JDamMrNkpud0FXVzlmK1pXMXM0cEMraEZtNjVFL3k2SA==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "nzkseaudcbosc",
      "s_game_name": "Fish Hunting: Li Kui Pi Yu",
      "s_game_alias": "FSGF2",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "40",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/nzkseaudcbosc.png",
      "d_create": "2021-09-04 15:18:24",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4UkpRaVlvcnliQml1QnliVWhDaVBORDRMdXR4MDZ4ZFVZNXd3V0hraU96cA==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "b8rzo7uzqt4sw",
      "s_game_name": "Fish Hunting: Golden Toad",
      "s_game_alias": "FSGF",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "18",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/b8rzo7uzqt4sw.png",
      "d_create": "2021-09-04 15:18:24",
      "d_update": "2024-04-01 12:59:29",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4VGtDaC9YZU5UUDFnRHI3aVRkdlBweE1NSlNVcmU2cGpaWWNlNU11SlRDOQ==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "qq5ocdypyeboy",
      "s_game_name": "Fish Hunter 2 EX - Novice",
      "s_game_alias": "FH2R1",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "151",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/qq5ocdypyeboy.png",
      "d_create": "2021-09-04 15:18:24",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4VGpxTTUyY1dXY0VCMUY4bEp6ZHFDd3h5T1Zxd2ZKdEJ3M3Rya01CamZHbA==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "xkhy6baryz7xs",
      "s_game_name": "Fish Hunter 2 EX - Newbie",
      "s_game_alias": "FH2R0",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "55",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/xkhy6baryz7xs.png",
      "d_create": "2021-09-04 15:18:23",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4WFJFdzBQb0tmK2xHcnBxNkI3OHEyZHJuKyt1VGw5Y1p0Vzh6bkp4Rmt6TQ==",
      "s_brand_code": "B009"
    },
    {
      "s_game_type": "Fishing",
      "s_game_code": "kk8nqm3cfwtng",
      "s_game_name": "Fish Haiba",
      "s_game_alias": "FHBH5",
      "s_specials": "",
      "s_flg_hot": "N",
      "s_flg_new": "N",
      "s_support_platform": "Desktop,Mobile",
      "s_sup_desktop": "Y",
      "s_sup_mobile": "Y",
      "s_order": "47",
      "i_width": "1280",
      "i_height": "720",
      "s_img": "https://img-game.tox2game.com/image/joker/kk8nqm3cfwtng.png",
      "d_create": "2021-09-04 15:18:23",
      "d_update": "2024-04-01 12:59:30",
      "s_create_by": "atbittuk",
      "s_update_by": "admin",
      "s_status": "A",
      "s_flg_favorite": "N",
      "id_favorite": "MXR2MGpmTm1DdC9VZ0srTUVNM2k4VlltampETmxuYm84V2JnU1BFVFBBZFVwazByd0w3bFVSQUJvcWJPN203Lw==",
      "s_brand_code": "B009"
    }
  ],
  "LOTTO": [],
  "ALL": [
    {
      "s_type": "CASINO",
      "s_pbrand_code": "SA",
      "s_brand_code": "B001",
      "s_brand_name": "SAGame",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/SA/LoginRequest"
    },
    {
      "s_type": "CASINO",
      "s_pbrand_code": "SEXY",
      "s_brand_code": "B003",
      "s_brand_name": "SexyGame",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/SEXY/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "PG",
      "s_brand_code": "B006",
      "s_brand_name": "PGSoft",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/PG/LoginRequestNew"
    },
    {
      "s_type": "CASINO",
      "s_pbrand_code": "PP",
      "s_brand_code": "B008",
      "s_brand_name": "PragmaticPlay - Live",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/PP/LIVE/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "JOKER",
      "s_brand_code": "B009",
      "s_brand_name": "JOKER",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/JOKER",
      "s_endpoint_access": "/JOKER/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "SIMPLEPLAY",
      "s_brand_code": "B010",
      "s_brand_name": "SimplePlay",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/SIMPLEPLAY/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "PPS",
      "s_brand_code": "B011",
      "s_brand_name": "PragmaticPlay - Slot",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/PPS",
      "s_endpoint_access": "/PP/SLOT/LoginRequest"
    },
    {
      "s_type": "SPORT",
      "s_pbrand_code": "SBO",
      "s_brand_code": "B012",
      "s_brand_name": "Sbobet",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/SBO/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "HB",
      "s_brand_code": "B016",
      "s_brand_name": "Habanero",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/HABANERO/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "JILI",
      "s_brand_code": "B017",
      "s_brand_name": "Jili",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "N",
      "s_lobby_url": "",
      "s_endpoint_access": "/Jili/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "FC",
      "s_brand_code": "B018",
      "s_brand_name": "Fachai",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/FC",
      "s_endpoint_access": "/FC/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "RSG",
      "s_brand_code": "B032",
      "s_brand_name": "Royal Slot Gaming",
      "s_status_agent": "A",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/RSG",
      "s_endpoint_access": "/RSG/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "YG",
      "s_brand_code": "B019",
      "s_brand_name": "Ygg",
      "s_status_agent": "C",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/YG",
      "s_endpoint_access": "/DCS/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "NLC",
      "s_brand_code": "B020",
      "s_brand_name": "No Limit City",
      "s_status_agent": "C",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/NLC",
      "s_endpoint_access": "/DCS/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "REL",
      "s_brand_code": "B022",
      "s_brand_name": "Relax",
      "s_status_agent": "C",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/REL",
      "s_endpoint_access": "/DCS/LoginRequest"
    },
    {
      "s_type": "SLOT",
      "s_pbrand_code": "PNG",
      "s_brand_code": "B027",
      "s_brand_name": "Play N GO",
      "s_status_agent": "C",
      "s_status": "A",
      "s_lobby_flg": "Y",
      "s_lobby_url": "/PNG",
      "s_endpoint_access": "/DCS/LoginRequest"
    }
  ],
  "HOTHIT": [],
  "FAVORITE": []
}